# config by Evan Koehler, forked by therealmodder

window:
  # adds padding to the terminal (looks great with rounded corners)
  padding:
    x: 20
    y: 20

  # sets background opacity to 0.1 (10%)
  # nah 100% opacity my guy
  opacity: 1.0

font:
  # I'm using JetBrains fonts, which I recommend, but feel free to edit it !
  # I'm using Noto Sans Mono cuz why not?
  normal:
    style: Medium
    family: Noto Sans Mono
  # sets font size to 14px
  # 11 my guy, my screen is only 720p
  size: 11.0

colors:
  # sets background color to light gray (#eee) and font color to white (#fff)
  # only changed the background to match bar background color
  primary:
    background: '#061115'
    foreground: '#ffffff'

shell:
  # sets my shell at startup (mine is fish but do not hesitate to put yours instead)
  # gonna use bash for maximum compatibility
  program: /bin/bash
  args:
    - --login
